services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/code/src
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
